version: "3.8"

services:
  web:
    build: .
    container_name: pavilion_app
    ports:
      - "8000:8000"
    env_file:
      - pavilion/.env
    depends_on:
      - db
    # volumes:
    #   - .:/app  # Syncs local files to the container (useful during development)

  db:
    image: postgres:16
    container_name: pavilion_db
    restart: always
    environment:
      POSTGRES_DB: pavilion_db
      POSTGRES_USER: pavilion_user
      POSTGRES_PASSWORD: pavilion_pass
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  pg_data:
